Updates

diff --git a/clean-dead-branches b/clean-dead-branches
--- a/clean-dead-branches
+++ b/clean-dead-branches
@@ -13,6 +13,14 @@ NOT_MERGED=()
 IFS='|'; IGNORE_PATTERN=${IGNORE_BRANCHES[*]} ; unset IFS
 REMOTE_BRANCHES=$(git branch -r | grep "$ORIGIN/" | grep -vE "$IGNORE_PATTERN")
 
+AGREEMENT=''
+read -p "AGREEMENT: THIS SCRIPT IS DESTRUCTIVE BY NATURE. BY USING THIS SCRIPT YOU AGREE TO HOLD THE DEVELOPERS, CONTRIBUTORS, AND ALL INVOLVED PARTIES, FREE FROM ALL LIABILITY. YOU AGREE THAT YOU ARE USING THIS SCRIPT AT YOUR OWN RISK, AND THAT YOU ARE TAKING FULL RESPONSIBILITY FOR ANY DAMAGED CAUSED. TYPE 'agree' TO AGREE TO THESE TERMS: " AGREEMENT
+
+if [[ "$AGREEMENT" != 'agree' ]]; then
+  echo "Agreement was not agreed to. Aborting."
+  exit 1
+fi
+
 echo -e "\e[93mCalculating for $TARGET_BRANCH...\e[0m"
 
 # Get all branch names
